config/routes.rb
Rails.application.routes.draw do
  resources :takeaway_menus
  resources :inhouse_menus
  resources :desserts
  resources :inindian_breads
  resources :inrice_dishes
  resources :injhas_special_biryani_dishes
  resources :invegetable_dishes
  resources :insea_foods
  resources :inlamb_dishes
  resources :inchicken_dishes
  resources :inchef_recommendations
  resources :intandooris
  resources :instarters
  root to: 'main#start_page'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dessert.rb
class Dessert < ApplicationRecord
end

app/models/inchef_recommendation.rb
class InchefRecommendation < ApplicationRecord
end

app/models/inchicken_dish.rb
class InchickenDish < ApplicationRecord
end

app/models/inindian_bread.rb
class InindianBread < ApplicationRecord
end

app/models/inlamb_dish.rb
class InlambDish < ApplicationRecord
end

app/models/inrice_dish.rb
class InriceDish < ApplicationRecord
end

app/models/insea_food.rb
class InseaFood < ApplicationRecord
end

app/models/instarter.rb
class Instarter < ApplicationRecord
end

app/models/intandoori.rb
class Intandoori < ApplicationRecord
end

app/models/invegetable_dish.rb
class InvegetableDish < ApplicationRecord
end

app/controllers/intandooris_controller.rb
class IntandoorisController < ApplicationController
  before_action :set_intandoori, only: [:show, :edit, :update, :destroy]

  # GET /intandooris
  # GET /intandooris.json
  def index
    @intandooris = Intandoori.all
  end

  # GET /intandooris/1
  # GET /intandooris/1.json
  def show
  end

  # GET /intandooris/new
  def new
    @intandoori = Intandoori.new
  end

  # GET /intandooris/1/edit
  def edit
  end

  # POST /intandooris
  # POST /intandooris.json
  def create
    @intandoori = Intandoori.new(intandoori_params)

    respond_to do |format|
      if @intandoori.save
        format.html { redirect_to @intandoori, notice: 'Intandoori was successfully created.' }
        format.json { render :show, status: :created, location: @intandoori }
      else
        format.html { render :new }
        format.json { render json: @intandoori.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /intandooris/1
  # PATCH/PUT /intandooris/1.json
  def update
    respond_to do |format|
      if @intandoori.update(intandoori_params)
        format.html { redirect_to @intandoori, notice: 'Intandoori was successfully updated.' }
        format.json { render :show, status: :ok, location: @intandoori }
      else
        format.html { render :edit }
        format.json { render json: @intandoori.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /intandooris/1
  # DELETE /intandooris/1.json
  def destroy
    @intandoori.destroy
    respond_to do |format|
      format.html { redirect_to intandooris_url, notice: 'Intandoori was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_intandoori
      @intandoori = Intandoori.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def intandoori_params
      params.require(:intandoori).permit(:name, :information, :price)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def start_page
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/desserts_helper.rb
module DessertsHelper
end

app/helpers/inhouse_menu_helper.rb
module InhouseMenuHelper
end

app/helpers/inindian_breads_helper.rb
module InindianBreadsHelper
end

app/helpers/inlamb_dishes_helper.rb
module InlambDishesHelper
end

app/helpers/inrice_dishes_helper.rb
module InriceDishesHelper
end

app/helpers/insea_foods_helper.rb
module InseaFoodsHelper
end

app/helpers/instarters_helper.rb
module InstartersHelper
end

app/helpers/intandooris_helper.rb
module IntandoorisHelper
end

app/helpers/takeaway_menu_helper.rb
module TakeawayMenuHelper
end

app/views/intandooris/_form.html.erb
<%= form_with(model: intandoori, local: true) do |form| %>
  <% if intandoori.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(intandoori.errors.count, "error") %> prohibited this intandoori from being saved:</h2>

      <ul>
      <% intandoori.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :information %>
    <%= form.text_area :information %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit 'Save Dish' %>
  </div>
<% end %>

app/views/intandooris/edit.html.erb
<h1>Editing Tandoori</h1>

<%= render 'form', intandoori: @intandoori %>

<%= link_to 'Show', @intandoori %> |
<%= link_to 'Back', intandooris_path %>

app/views/intandooris/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tandooris</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Information</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @intandooris.each do |intandoori| %>
      <tr>
        <td><%= intandoori.name %></td>
        <td><%= intandoori.information %></td>
        <td>£<%= intandoori.price %></td>
        <td><%= link_to 'Show', intandoori %></td>
        <td><%= link_to 'Edit', edit_intandoori_path(intandoori) %></td>
        <td><%= link_to 'Destroy', intandoori, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tandoori', new_intandoori_path %>

app/views/intandooris/new.html.erb
<h1>New Tandoori</h1>

<%= render 'form', intandoori: @intandoori %>

<%= link_to 'Back', intandooris_path %>

app/views/intandooris/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @intandoori.name %>
</p>

<p>
  <strong>Information:</strong>
  <%= @intandoori.information %>
</p>

<p>
  <strong>Price:</strong>
  <%= @intandoori.price %>
</p>

<%= link_to 'Edit', edit_intandoori_path(@intandoori) %> |
<%= link_to 'Back', intandooris_path %>