config/routes.rb
Rails.application.routes.draw do
  resources :takeaway_menus
  resources :inhouse_menus
  resources :desserts
  resources :inindian_breads
  resources :inrice_dishes
  resources :injhas_special_biryani_dishes
  resources :invegetable_dishes
  resources :insea_foods
  resources :inlamb_dishes
  resources :inchicken_dishes
  resources :inchef_recommendations
  resources :intandooris
  resources :instarters
  root to: 'main#start_page'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dessert.rb
class Dessert < ApplicationRecord
end

app/models/inchef_recommendation.rb
class InchefRecommendation < ApplicationRecord
end

app/models/inchicken_dish.rb
class InchickenDish < ApplicationRecord
end

app/models/inindian_bread.rb
class InindianBread < ApplicationRecord
end

app/models/inlamb_dish.rb
class InlambDish < ApplicationRecord
end

app/models/inrice_dish.rb
class InriceDish < ApplicationRecord
end

app/models/insea_food.rb
class InseaFood < ApplicationRecord
end

app/models/instarter.rb
class Instarter < ApplicationRecord
end

app/models/intandoori.rb
class Intandoori < ApplicationRecord
end

app/models/invegetable_dish.rb
class InvegetableDish < ApplicationRecord
end

app/controllers/inindian_breads_controller.rb
class InindianBreadsController < ApplicationController
  before_action :set_inindian_bread, only: [:show, :edit, :update, :destroy]

  # GET /inindian_breads
  # GET /inindian_breads.json
  def index
    @inindian_breads = InindianBread.all
  end

  # GET /inindian_breads/1
  # GET /inindian_breads/1.json
  def show
  end

  # GET /inindian_breads/new
  def new
    @inindian_bread = InindianBread.new
  end

  # GET /inindian_breads/1/edit
  def edit
  end

  # POST /inindian_breads
  # POST /inindian_breads.json
  def create
    @inindian_bread = InindianBread.new(inindian_bread_params)

    respond_to do |format|
      if @inindian_bread.save
        format.html { redirect_to @inindian_bread, notice: 'Inindian bread was successfully created.' }
        format.json { render :show, status: :created, location: @inindian_bread }
      else
        format.html { render :new }
        format.json { render json: @inindian_bread.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inindian_breads/1
  # PATCH/PUT /inindian_breads/1.json
  def update
    respond_to do |format|
      if @inindian_bread.update(inindian_bread_params)
        format.html { redirect_to @inindian_bread, notice: 'Inindian bread was successfully updated.' }
        format.json { render :show, status: :ok, location: @inindian_bread }
      else
        format.html { render :edit }
        format.json { render json: @inindian_bread.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inindian_breads/1
  # DELETE /inindian_breads/1.json
  def destroy
    @inindian_bread.destroy
    respond_to do |format|
      format.html { redirect_to inindian_breads_url, notice: 'Inindian bread was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inindian_bread
      @inindian_bread = InindianBread.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inindian_bread_params
      params.require(:inindian_bread).permit(:name, :information, :price)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def start_page
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/desserts_helper.rb
module DessertsHelper
end

app/helpers/inhouse_menu_helper.rb
module InhouseMenuHelper
end

app/helpers/inindian_breads_helper.rb
module InindianBreadsHelper
end

app/helpers/inlamb_dishes_helper.rb
module InlambDishesHelper
end

app/helpers/inrice_dishes_helper.rb
module InriceDishesHelper
end

app/helpers/insea_foods_helper.rb
module InseaFoodsHelper
end

app/helpers/instarters_helper.rb
module InstartersHelper
end

app/helpers/intandooris_helper.rb
module IntandoorisHelper
end

app/helpers/takeaway_menu_helper.rb
module TakeawayMenuHelper
end

app/views/inindian_breads/_form.html.erb
<%= form_with(model: inindian_bread, local: true) do |form| %>
  <% if inindian_bread.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inindian_bread.errors.count, "error") %> prohibited this inindian_bread from being saved:</h2>

      <ul>
      <% inindian_bread.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :information %>
    <%= form.text_area :information %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit 'Save Dish' %>
  </div>
<% end %>

app/views/inindian_breads/edit.html.erb
<h1>Editing Indian Bread</h1>

<%= render 'form', inindian_bread: @inindian_bread %>

<%= link_to 'Show', @inindian_bread %> |
<%= link_to 'Back', inindian_breads_path %>

app/views/inindian_breads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Indian Breads</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Information</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inindian_breads.each do |inindian_bread| %>
      <tr>
        <td><%= inindian_bread.name %></td>
        <td><%= inindian_bread.information %></td>
        <td>£<%= inindian_bread.price %></td>
        <td><%= link_to 'Show', inindian_bread %></td>
        <td><%= link_to 'Edit', edit_inindian_bread_path(inindian_bread) %></td>
        <td><%= link_to 'Destroy', inindian_bread, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Indian Bread', new_inindian_bread_path %>

app/views/inindian_breads/new.html.erb
<h1>New Indian Bread</h1>

<%= render 'form', inindian_bread: @inindian_bread %>

<%= link_to 'Back', inindian_breads_path %>

app/views/inindian_breads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @inindian_bread.name %>
</p>

<p>
  <strong>Information:</strong>
  <%= @inindian_bread.information %>
</p>

<p>
  <strong>Price:</strong>
  <%= @inindian_bread.price %>
</p>

<%= link_to 'Edit', edit_inindian_bread_path(@inindian_bread) %> |
<%= link_to 'Back', inindian_breads_path %>