config/routes.rb
Rails.application.routes.draw do
  resources :takeaway_menus
  resources :inhouse_menus
  resources :desserts
  resources :inindian_breads
  resources :inrice_dishes
  resources :injhas_special_biryani_dishes
  resources :invegetable_dishes
  resources :insea_foods
  resources :inlamb_dishes
  resources :inchicken_dishes
  resources :inchef_recommendations
  resources :intandooris
  resources :instarters
  root to: 'main#start_page'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dessert.rb
class Dessert < ApplicationRecord
end

app/models/inchef_recommendation.rb
class InchefRecommendation < ApplicationRecord
end

app/models/inchicken_dish.rb
class InchickenDish < ApplicationRecord
end

app/models/inindian_bread.rb
class InindianBread < ApplicationRecord
end

app/models/inlamb_dish.rb
class InlambDish < ApplicationRecord
end

app/models/inrice_dish.rb
class InriceDish < ApplicationRecord
end

app/models/insea_food.rb
class InseaFood < ApplicationRecord
end

app/models/instarter.rb
class Instarter < ApplicationRecord
end

app/models/intandoori.rb
class Intandoori < ApplicationRecord
end

app/models/invegetable_dish.rb
class InvegetableDish < ApplicationRecord
end

app/controllers/inrice_dishes_controller.rb
class InriceDishesController < ApplicationController
  before_action :set_inrice_dish, only: [:show, :edit, :update, :destroy]

  # GET /inrice_dishes
  # GET /inrice_dishes.json
  def index
    @inrice_dishes = InriceDish.all
  end

  # GET /inrice_dishes/1
  # GET /inrice_dishes/1.json
  def show
  end

  # GET /inrice_dishes/new
  def new
    @inrice_dish = InriceDish.new
  end

  # GET /inrice_dishes/1/edit
  def edit
  end

  # POST /inrice_dishes
  # POST /inrice_dishes.json
  def create
    @inrice_dish = InriceDish.new(inrice_dish_params)

    respond_to do |format|
      if @inrice_dish.save
        format.html { redirect_to @inrice_dish, notice: 'Inrice dish was successfully created.' }
        format.json { render :show, status: :created, location: @inrice_dish }
      else
        format.html { render :new }
        format.json { render json: @inrice_dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inrice_dishes/1
  # PATCH/PUT /inrice_dishes/1.json
  def update
    respond_to do |format|
      if @inrice_dish.update(inrice_dish_params)
        format.html { redirect_to @inrice_dish, notice: 'Inrice dish was successfully updated.' }
        format.json { render :show, status: :ok, location: @inrice_dish }
      else
        format.html { render :edit }
        format.json { render json: @inrice_dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inrice_dishes/1
  # DELETE /inrice_dishes/1.json
  def destroy
    @inrice_dish.destroy
    respond_to do |format|
      format.html { redirect_to inrice_dishes_url, notice: 'Inrice dish was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inrice_dish
      @inrice_dish = InriceDish.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inrice_dish_params
      params.require(:inrice_dish).permit(:name, :information, :price)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def start_page
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/desserts_helper.rb
module DessertsHelper
end

app/helpers/inhouse_menu_helper.rb
module InhouseMenuHelper
end

app/helpers/inindian_breads_helper.rb
module InindianBreadsHelper
end

app/helpers/inlamb_dishes_helper.rb
module InlambDishesHelper
end

app/helpers/inrice_dishes_helper.rb
module InriceDishesHelper
end

app/helpers/insea_foods_helper.rb
module InseaFoodsHelper
end

app/helpers/instarters_helper.rb
module InstartersHelper
end

app/helpers/intandooris_helper.rb
module IntandoorisHelper
end

app/helpers/takeaway_menu_helper.rb
module TakeawayMenuHelper
end

app/views/inrice_dishes/_form.html.erb
<%= form_with(model: inrice_dish, local: true) do |form| %>
  <% if inrice_dish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inrice_dish.errors.count, "error") %> prohibited this inrice_dish from being saved:</h2>

      <ul>
      <% inrice_dish.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :information %>
    <%= form.text_area :information %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit 'Save Dish' %>
  </div>
<% end %>

app/views/inrice_dishes/edit.html.erb
<h1>Editing Rice Dish</h1>

<%= render 'form', inrice_dish: @inrice_dish %>

<%= link_to 'Show', @inrice_dish %> |
<%= link_to 'Back', inrice_dishes_path %>

app/views/inrice_dishes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rice Dishes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Information</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inrice_dishes.each do |inrice_dish| %>
      <tr>
        <td><%= inrice_dish.name %></td>
        <td><%= inrice_dish.information %></td>
        <td>£<%= inrice_dish.price %></td>
        <td><%= link_to 'Show', inrice_dish %></td>
        <td><%= link_to 'Edit', edit_inrice_dish_path(inrice_dish) %></td>
        <td><%= link_to 'Destroy', inrice_dish, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rice Dish', new_inrice_dish_path %>

app/views/inrice_dishes/new.html.erb
<h1>New Rice Dish</h1>

<%= render 'form', inrice_dish: @inrice_dish %>

<%= link_to 'Back', inrice_dishes_path %>

app/views/inrice_dishes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @inrice_dish.name %>
</p>

<p>
  <strong>Information:</strong>
  <%= @inrice_dish.information %>
</p>

<p>
  <strong>Price:</strong>
  <%= @inrice_dish.price %>
</p>

<%= link_to 'Edit', edit_inrice_dish_path(@inrice_dish) %> |
<%= link_to 'Back', inrice_dishes_path %>